### ISSUE TITLE
Design the database

### ISSUE THREAD

**Issue by jahzielv** [JIC-8130/jic-8130-yca#45]
## TODO:
- [ ] Finalize data that will be entered into the db.
- [ ] Finalize what metrics will be created
- [ ] Lay out the tables for our database!
